language: node_js

node_js:
  - "node"

branches:
  only:
    - hexo

before_install:
  - npm install hexo-cli -g
  - npm i -g firebase-tools
  - git config --global push.default matching
  - git config --global user.name "leon"
  - git config --global user.email "i@leonvision.online"
  - sed -i'' "/^ *repo/s~github\.com~${ACCESS_TOKEN}@github.com~" _config.yml

install:
  - npm install

script:
  # - git submodule init      # 用于更新主题
  # - git submodule update
  - hexo clean
  - hexo d -g
  

cache:
  directories:
    - node_modules


# after_success:
#   - firebase login --reauth
#   - firebase deploy --non-interactive --token ${FIREBASE_TOKEN}

deploy:
  provider: firebase
  token:
    secure: ${FIREBASE_TOKEN}
  on:
    branch: hexo