language: node_js
node_js:
- node
branches:
  only:
  - hexo
before_install:
- npm install hexo-cli -g
# - npm i -g firebase-tools
- git config --global push.default matching
- git config --global user.name "leon"
- git config --global user.email "i@leonvision.online"
- sed -i'' "/^ *repo/s~github\.com~${GITHUB_TOKEN}@github.com~" _config.yml
install:
- npm install
script:
- hexo clean
- hexo d -g
cache:
  directories:
  - node_modules
env:
  global:
  # - GIT_PAGE_REF: github.com/qzi/qzi.github.io.git
  #- secure: I3EIHvysnL50yQPdu5jRZfX3+A+3TlDlcTgd9GZQ7HbKjIdhx8cYU1bZUUv3sAXJnAS9nU3QFy3Q/bccshrFdh6cEww+qcJ0MuvUahqe99yRkaevaXTw9uCm/p+lUORUQcg6mfhc30l8bb469a/ldLBXao6HHTsVRYVBm5g3VcFpxU0/zaufSxgwek7e5PlGB0YWUC93MBiOPpEin4ikVVoFWDP1KsEbmubRrW/LpysUZIiXy13qdQvtKRAoQ78UTmt2o8FFcHvWRUMleTyi63iJqVB7OSOXGnjPnp2fdIhVyXs50VPvY5UUOw1qyhPkw/D1HUUpsorE/xvDNsJFy4/anUHppjKYTBA/RbVRZp/tTH1cLn0wpHq+L/RsKh/G/G7q/2htEDcay+/fYxGYClCDZeMGvOrJUkXz996miwHWojYlGwrcyRvvOmRZz5jISlB4KAlaJHWWaVzG1xCFTeektVeSrOM8hMZ9c0JVi/8zwYNecsw/zBJmrWBSzdAyxnxIEmfmmLQXArtLUvq3FGs/L02qE0ZlaFisNRJ1r9DvLZ1Hats2a88kaU2B+LJQR4crMZuWneuoW1m+2du1HpP0oy4i/a/uRdyVgBvqnE+u2EH16VhAYk5Wwu/+giMWi3wMMDMJnEHt5EodL4kKwglVhjNdKsyH7sgOcXELbIY=
  - secure: I3EIHvysnL50yQPdu5jRZfX3+A+3TlDlcTgd9GZQ7HbKjIdhx8cYU1bZUUv3sAXJnAS9nU3QFy3Q/bccshrFdh6cEww+qcJ0MuvUahqe99yRkaevaXTw9uCm/p+lUORUQcg6mfhc30l8bb469a/ldLBXao6HHTsVRYVBm5g3VcFpxU0/zaufSxgwek7e5PlGB0YWUC93MBiOPpEin4ikVVoFWDP1KsEbmubRrW/LpysUZIiXy13qdQvtKRAoQ78UTmt2o8FFcHvWRUMleTyi63iJqVB7OSOXGnjPnp2fdIhVyXs50VPvY5UUOw1qyhPkw/D1HUUpsorE/xvDNsJFy4/anUHppjKYTBA/RbVRZp/tTH1cLn0wpHq+L/RsKh/G/G7q/2htEDcay+/fYxGYClCDZeMGvOrJUkXz996miwHWojYlGwrcyRvvOmRZz5jISlB4KAlaJHWWaVzG1xCFTeektVeSrOM8hMZ9c0JVi/8zwYNecsw/zBJmrWBSzdAyxnxIEmfmmLQXArtLUvq3FGs/L02qE0ZlaFisNRJ1r9DvLZ1Hats2a88kaU2B+LJQR4crMZuWneuoW1m+2du1HpP0oy4i/a/uRdyVgBvqnE+u2EH16VhAYk5Wwu/+giMWi3wMMDMJnEHt5EodL4kKwglVhjNdKsyH7sgOcXELbIY=

deploy:
  skip_cleanup: false
  provider: firebase
  token:
    secure: oi3MqQ5QQRIM/Cy1LSmoI7hh8WIsmmZiSRAfXiGHxxRQ9e0XFU62m8BeWoRe8qxRe5hPc0hVZtt3IQMq64Wv2qUkcC0ZgEg9F+1MLbXRy3XvnFlBXh1V53hS5+QlF5iz7TtwjgEjh1bgCSa9TlINExgXg7D0T35TvfzgAI8Mj/HNae94R2q1NtEuR8ZAP7YnsEUAT1Ylsnf9fgPmiEH8EWXW41IkBYPQ92qnMuScpUtSjsoc5vOoLJ6PrBUTM1UM5y7IOTl5RITrVjSvDxkOT7iJNAc0MCQ4u8eu99xDYogOgvgZocxtN29yXCi2BzcXaglyrjwT0eoQ61vMP1VlraX0Jc7UsYD4yqVk7w9+/9+++AZv9vZhUl95Gj1/PMCUmJdHyuI0xe6WzxmpkRQsgg+XbBUpKBSVuiQ0A0jN+woeRhYNrnC4aVdEJIkciyw+fRyP05tdiUh8/D8RaOAbCfdw+0biI7ZWvU8zuag7yUlZuDS4PClUtaa4rwWpzk9ZRt4LAglsc6D2FJN7i4dKdsu5txxSBiv9KZ0tVx3b+cW2NOAfKUsQhIFqujn9cxdneEXXrzfRXf/CaPTkbPZ/E256lnf3lPONvHilxBNIZ/S1kRnYNj9t5woThQDoXfLMOcdrWyNYpnrNnH58xX0m/zAzyS6va5gU7MLaKUnC66M=
  project: $FIREBASE_PROJECT
  on:
    all_branches: true
    # branches: master
