
{# google adsense body #}
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle"
     style="display:block; text-align:center;"
     data-ad-layout="in-article"
     data-ad-format="fluid"
     data-ad-client="ca-pub-6391042540548664"
     data-ad-slot="7494260686"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>

{# google adsense end #}

